export interface SeedSymptom {
  title: string;
  slug: string;
  iconName: string | null;
  description: string;
  popularFor: string[];
  recoveryEstimate: string | null;
  image: string | null;
  symptomsList: string;
  treatment: string;
  sortOrder: number;
  active: boolean;
}

export const SYMPTOMS_DATA: SeedSymptom[] = [
  {
    title: "Back Pain",
    slug: "back-pain",
    iconName: null,
    description: "Pain along the spine caused by muscle strain, poor posture, disc issues, or prolonged sitting/standing.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "https://i0.wp.com/www.kvphysiotherapy.com/wp-content/uploads/2021/04/WhatsApp-Image-2021-04-19-at-8.29.41-PM.jpeg?resize=1140%2C855&ssl=1",
    symptomsList: "Dull or sharp pain in upper/lower back; Stiffness on waking; Pain worsening with bending or sitting long hours; Muscle spasm",
    treatment: "Postural correction, core-strengthening exercises, manual therapy, heat/electrotherapy, ergonomic advice, stretching program.",
    sortOrder: 1,
    active: true,
  },
  {
    title: "Neck Pain",
    slug: "neck-pain-cervical-spondylosis",
    iconName: null,
    description: "Wear-and-tear or strain affecting the cervical (neck) spine, common with age or desk-bound work.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "https://ispcclinic.com/wp-content/uploads/2026/02/b8a18da6-5a02-4d64-b684-e55fd9b488d5-1024x576.jpg",
    symptomsList: "Neck stiffness; Pain radiating to shoulders/arms; Headaches; Reduced neck rotation; Tingling in hands",
    treatment: "Cervical traction, manual mobilization, neck-strengthening exercises, posture retraining, heat therapy.",
    sortOrder: 2,
    active: true,
  },
  {
    title: "Sciatica",
    slug: "sciatica",
    iconName: null,
    description: "Irritation or compression of the sciatic nerve, usually from a disc issue or piriformis tightness.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "https://www.sakraworldhospital.com/assets/images/blogs/sciatica.webp",
    symptomsList: "Shooting pain from lower back through hip and down the leg; Numbness; Tingling; Worse on sitting",
    treatment: "Nerve mobilization, stretching (piriformis, hamstrings), core strengthening, postural correction, heat/cold therapy.",
    sortOrder: 3,
    active: true,
  },
  {
    title: "Frozen Shoulder",
    slug: "frozen-shoulder",
    iconName: null,
    description: "Progressive stiffening and thickening of the shoulder joint capsule, restricting movement.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "8-16 weeks",
    image: "https://www.shutterstock.com/image-photo/indian-physiotherapist-help-elderly-man-260nw-2580442099.jpg",
    symptomsList: "Gradual shoulder pain; Severe stiffness; Difficulty raising arm; Night pain",
    treatment: "Capsular stretching, mobilization techniques, pendulum exercises, ultrasound therapy, progressive range-of-motion program.",
    sortOrder: 4,
    active: true,
  },
  {
    title: "Knee Osteoarthritis",
    slug: "osteoarthritis",
    iconName: null,
    description: "Degeneration of joint cartilage leading to bone-on-bone friction, common with aging.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "https://www.carehospitals.com/ckfinder/userfiles/images/arthritis.webp",
    symptomsList: "Joint pain; Stiffness (especially morning); Swelling; Reduced range of motion; Crepitus",
    treatment: "Low-impact strengthening, range-of-motion exercises, joint protection education, weight-management guidance, pain-relief modalities.",
    sortOrder: 5,
    active: true,
  },
  {
    title: "Spondylosis",
    slug: "spondylosis",
    iconName: null,
    description: "Age-related wear-and-tear of the spine's discs and joints, causing stiffness and, at times, nerve-related pain.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "https://ispcclinic.com/wp-content/uploads/2026/02/b8a18da6-5a02-4d64-b684-e55fd9b488d5-1024x576.jpg",
    symptomsList: "Spinal stiffness; Pain radiating to arms or legs; Headaches; Reduced flexibility; Tingling or numbness",
    treatment: "Spinal mobilization, traction, postural retraining, strengthening of supportive muscles, heat therapy.",
    sortOrder: 6,
    active: true,
  },
  {
    title: "ACL Tear",
    slug: "ligament-sprains",
    iconName: null,
    description: "Stretching or tearing of knee ligaments (especially the ACL) from sudden twisting or impact.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/ligament-sprains.jpg",
    symptomsList: "Swelling; Instability; Pain with movement; Bruising",
    treatment: "Bracing, proprioception training, progressive strengthening, sport-specific rehab; surgical referral if severe.",
    sortOrder: 7,
    active: true,
  },
  {
    title: "Rotator Cuff Injury",
    slug: "rotator-cuff-strain",
    iconName: null,
    description: "Overstretching or minor tearing of shoulder rotator cuff muscles or tendons.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/rotator-cuff-strain.jpg",
    symptomsList: "Shoulder pain with overhead movement; Weakness; Discomfort at rest",
    treatment: "Rotator cuff and scapular strengthening, activity modification, manual therapy.",
    sortOrder: 8,
    active: true,
  },
  {
    title: "Tennis Elbow",
    slug: "tennis-elbow",
    iconName: null,
    description: "Inflammation of tendons on the outer elbow from repetitive wrist/arm strain.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/tennis-elbow.jpg",
    symptomsList: "Pain on outer elbow; Weak grip; Pain gripping or lifting objects",
    treatment: "Eccentric strengthening exercises, forearm stretching, bracing, ultrasound/laser therapy.",
    sortOrder: 9,
    active: true,
  },
  {
    title: "Ankle Sprain",
    slug: "ankle-sprain",
    iconName: null,
    description: "Stretching or tearing of ligaments around the ankle, usually from a twisting injury.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/ankle-sprain.jpg",
    symptomsList: "Swelling; Bruising; Pain on weight-bearing; Instability",
    treatment: "RICE protocol initially, balance/proprioception training, progressive strengthening, taping.",
    sortOrder: 10,
    active: true,
  },
  {
    title: "Stress Fracture",
    slug: "stress-fractures",
    iconName: null,
    description: "Small cracks in bone from repetitive impact or overuse.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "6-8 weeks",
    image: "/images/symptoms/stress-fractures.jpg",
    symptomsList: "Localized pain that worsens with activity; Tenderness; Mild swelling",
    treatment: "Load management, gradual return-to-activity program, strengthening, footwear/biomechanics review.",
    sortOrder: 11,
    active: true,
  },
  {
    title: "Hamstring Strain",
    slug: "muscle-pulls-strains",
    iconName: null,
    description: "Overstretching or tearing of the hamstring muscles at the back of the thigh during physical activity.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/muscle-pulls-strains.jpg",
    symptomsList: "Sudden pain at the back of thigh; Tightness; Swelling; Reduced strength",
    treatment: "RICE, progressive stretching and strengthening, return-to-play protocol.",
    sortOrder: 12,
    active: true,
  },
  {
    title: "Stroke",
    slug: "stroke-rehabilitation",
    iconName: null,
    description: "Recovery therapy after a stroke affecting brain blood supply, causing motor/sensory deficits.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "3-12 months",
    image: "https://t3.ftcdn.net/jpg/06/64/72/70/360_F_664727033_DWgYkD9ZRgPYYIkAu2O5jvM9d8nVtjS.jpg",
    symptomsList: "Weakness on one side; Speech difficulty; Balance problems; Coordination loss",
    treatment: "Task-specific motor retraining, balance training, gait re-education, functional exercises.",
    sortOrder: 13,
    active: true,
  },
  {
    title: "Parkinson's Disease",
    slug: "parkinsons-disease",
    iconName: null,
    description: "A progressive neurological disorder affecting movement control.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/parkinsons-disease.jpg",
    symptomsList: "Tremors; Muscle rigidity; Slow movement; Balance problems; Shuffling gait",
    treatment: "Gait training, balance exercises, flexibility work, functional mobility training.",
    sortOrder: 14,
    active: true,
  },
  {
    title: "Multiple Sclerosis (MS)",
    slug: "multiple-sclerosis",
    iconName: null,
    description: "An autoimmune condition affecting the central nervous system.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/multiple-sclerosis.jpg",
    symptomsList: "Fatigue; Muscle weakness; Balance issues; Numbness; Coordination difficulty",
    treatment: "Energy conservation strategies, balance and strengthening exercises, stretching, fatigue-managed activity plans.",
    sortOrder: 15,
    active: true,
  },
  {
    title: "Spinal Cord Injury",
    slug: "spinal-cord-injury",
    iconName: null,
    description: "Damage to the spinal cord causing loss of function below the injury level.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/spinal-cord-injury.jpg",
    symptomsList: "Weakness or paralysis; Sensory loss; Muscle spasticity; Bladder/bowel changes",
    treatment: "Mobility and transfer training, strengthening of functional muscles, wheelchair skills training, spasticity management.",
    sortOrder: 16,
    active: true,
  },
  {
    title: "Cerebral Palsy",
    slug: "cerebral-palsy",
    iconName: null,
    description: "A group of disorders affecting movement and posture due to early brain development issues.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/cerebral-palsy.jpg",
    symptomsList: "Muscle stiffness or floppiness; Poor coordination; Delayed motor milestones",
    treatment: "Developmental therapy, stretching, strengthening, gait training, assistive device training.",
    sortOrder: 17,
    active: true,
  },
  {
    title: "Traumatic Brain Injury",
    slug: "traumatic-brain-injury",
    iconName: null,
    description: "Recovery therapy after a head injury that has affected movement, balance, or coordination.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "3-12 months",
    image: "https://t3.ftcdn.net/jpg/06/64/72/70/360_F_664727033_DWgYkD9ZRgPYYIkAu2O5jvM9d8nVtjS.jpg",
    symptomsList: "Balance problems; Weakness; Coordination difficulty; Fatigue; Sensitivity to overstimulation",
    treatment: "Balance and coordination training, graded strengthening, task-specific functional retraining, fatigue management.",
    sortOrder: 18,
    active: true,
  },
  {
    title: "Cerebral Palsy in Children",
    slug: "cerebral-palsy-children",
    iconName: null,
    description: "A movement and posture disorder from early brain development issues, managed early in childhood.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/cerebral-palsy-children.jpg",
    symptomsList: "Abnormal muscle tone; Delayed milestones; Coordination difficulties",
    treatment: "Early intervention therapy, stretching, functional movement training, family education.",
    sortOrder: 19,
    active: true,
  },
  {
    title: "Developmental Delay",
    slug: "developmental-delay",
    iconName: null,
    description: "Slower-than-typical achievement of motor milestones in children.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "3-12 months",
    image: "/images/symptoms/developmental-delay.jpg",
    symptomsList: "Delayed sitting/crawling/walking; Poor coordination for age",
    treatment: "Play-based motor development therapy, strengthening, milestone-focused activities.",
    sortOrder: 20,
    active: true,
  },
  {
    title: "Muscular Dystrophy",
    slug: "muscular-dystrophy",
    iconName: null,
    description: "A genetic disorder causing progressive muscle weakness.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/muscular-dystrophy.jpg",
    symptomsList: "Progressive weakness; Difficulty walking/climbing stairs; Frequent falls",
    treatment: "Gentle strengthening, stretching to prevent contractures, mobility aids training, breathing exercises.",
    sortOrder: 21,
    active: true,
  },
  {
    title: "Infant Torticollis",
    slug: "torticollis",
    iconName: null,
    description: "Tightness of neck muscles causing the head to tilt to one side, common in infants.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "3-6 months",
    image: "/images/symptoms/torticollis.jpg",
    symptomsList: "Head tilt; Limited neck rotation; Asymmetrical head shape in infants",
    treatment: "Stretching exercises, positioning techniques, strengthening of opposite-side muscles.",
    sortOrder: 22,
    active: true,
  },
  {
    title: "Scoliosis in Children",
    slug: "scoliosis-postural-deformities",
    iconName: null,
    description: "Abnormal sideways curvature of the spine developing or progressing during childhood growth spurts.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/scoliosis-postural-deformities.jpg",
    symptomsList: "Visible spinal curve; Uneven shoulders/hips; Back pain; Fatigue with prolonged standing",
    treatment: "Scoliosis-specific exercises (e.g., Schroth method), postural correction, core strengthening, bracing guidance where needed.",
    sortOrder: 23,
    active: true,
  },
  {
    title: "Coordination Difficulties in Children",
    slug: "coordination-difficulties-children",
    iconName: null,
    description: "Difficulty planning and executing coordinated movements (motor skills) for a child's age.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "3-12 months",
    image: "/images/symptoms/developmental-delay.jpg",
    symptomsList: "Clumsy or uncoordinated movement; Difficulty with balance, catching, or fine-motor tasks; Avoidance of physical play",
    treatment: "Balance and coordination activities, gross- and fine-motor skill training, play-based movement therapy.",
    sortOrder: 24,
    active: true,
  },
  {
    title: "COPD",
    slug: "copd",
    iconName: null,
    description: "A progressive lung disease causing airflow limitation.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/copd.jpg",
    symptomsList: "Breathlessness; Chronic cough; Fatigue; Reduced exercise tolerance",
    treatment: "Pulmonary rehabilitation, breathing exercises, airway clearance techniques, graded exercise training.",
    sortOrder: 25,
    active: true,
  },
  {
    title: "Post-COVID Recovery",
    slug: "post-covid-pulmonary-rehabilitation",
    iconName: null,
    description: "Recovery therapy for lingering respiratory and functional effects after COVID-19.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/post-covid-pulmonary-rehabilitation.jpg",
    symptomsList: "Breathlessness; Fatigue; Reduced stamina; Muscle weakness",
    treatment: "Breathing exercises, graded aerobic reconditioning, strength training, fatigue management.",
    sortOrder: 26,
    active: true,
  },
  {
    title: "Asthma",
    slug: "asthma-breathing-exercises",
    iconName: null,
    description: "A chronic condition causing airway inflammation and breathing difficulty.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/asthma-breathing-exercises.jpg",
    symptomsList: "Wheezing; Breathlessness; Chest tightness; Coughing",
    treatment: "Breathing retraining, diaphragmatic breathing exercises, posture correction, graded activity.",
    sortOrder: 27,
    active: true,
  },
  {
    title: "Post-CABG Rehabilitation",
    slug: "cardiac-rehabilitation",
    iconName: null,
    description: "Structured exercise and education program after coronary artery bypass graft (CABG) or other heart surgery.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "8-12 weeks",
    image: "/images/symptoms/cardiac-rehabilitation.jpg",
    symptomsList: "Reduced stamina; Weakness; Anxiety about exertion; Breathlessness on activity",
    treatment: "Graded aerobic exercise, breathing exercises, monitored strength training, lifestyle education.",
    sortOrder: 28,
    active: true,
  },
  {
    title: "Bronchiectasis",
    slug: "bronchiectasis",
    iconName: null,
    description: "Permanent widening of lung airways causing chronic cough and repeated chest infections.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/chest-physiotherapy.jpg",
    symptomsList: "Chronic productive cough; Breathlessness; Frequent chest infections; Fatigue",
    treatment: "Airway clearance techniques, postural drainage, breathing exercises, graded exercise training.",
    sortOrder: 29,
    active: true,
  },
  {
    title: "ICU Recovery",
    slug: "icu-recovery",
    iconName: null,
    description: "Rehabilitation after a critical-illness stay in the ICU to regain strength, movement, and independence.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/post-hospitalization-recovery.jpg",
    symptomsList: "Severe weakness; Muscle wasting; Reduced mobility; Breathlessness; Fatigue",
    treatment: "Graded strengthening, early mobilization, breathing exercises, fatigue-managed functional retraining.",
    sortOrder: 30,
    active: true,
  },
  {
    title: "Osteoporosis",
    slug: "osteoporosis-related-fragility",
    iconName: null,
    description: "Increased fracture risk due to reduced bone density.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/osteoporosis-related-fragility.jpg",
    symptomsList: "Often silent; May include back pain or stooped posture",
    treatment: "Weight-bearing and resistance exercises, balance training, posture education, fall-prevention strategies.",
    sortOrder: 31,
    active: true,
  },
  {
    title: "Balance Disorders",
    slug: "balance-coordination-disorders",
    iconName: null,
    description: "Impaired ability to maintain stability, common with aging, causing unsteadiness and fall risk.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/balance-coordination-disorders.jpg",
    symptomsList: "Frequent falls; Unsteadiness; Difficulty with coordinated movements",
    treatment: "Balance training, proprioceptive exercises, strength and gait training.",
    sortOrder: 32,
    active: true,
  },
  {
    title: "Fall Prevention",
    slug: "fall-risk-balance-training",
    iconName: null,
    description: "Assessment and training to reduce the risk of falls in older adults.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/fall-risk-balance-training.jpg",
    symptomsList: "Unsteady gait; History of falls; Reduced confidence in mobility",
    treatment: "Balance exercises, strength training, gait aids assessment, home-safety education.",
    sortOrder: 33,
    active: true,
  },
  {
    title: "Hip Fracture Rehabilitation",
    slug: "hip-fracture-rehabilitation",
    iconName: null,
    description: "Recovery program after a hip fracture or hip surgery to restore mobility and independence.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/post-hip-replacement-rehab.jpg",
    symptomsList: "Weakness; Limited hip movement; Difficulty walking; Balance problems",
    treatment: "Progressive strengthening, gait retraining, balance exercises, mobility and stair training.",
    sortOrder: 34,
    active: true,
  },
  {
    title: "Age-Related Deconditioning",
    slug: "age-related-mobility-decline",
    iconName: null,
    description: "Gradual reduction in strength, flexibility, and mobility with aging.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "Ongoing management",
    image: "https://advaithability.com/wp-content/uploads/2026/04/Geriatric-Physiotherapy-in-Dehradun.jpg.jpeg",
    symptomsList: "Slower walking; Difficulty rising from chairs; Reduced endurance",
    treatment: "Functional strengthening, flexibility exercises, endurance training.",
    sortOrder: 35,
    active: true,
  },
  {
    title: "Knee and Hip Arthritis",
    slug: "knee-hip-arthritis",
    iconName: null,
    description: "Joint cartilage wear-and-tear in the knees and hips causing pain and stiffness, common with aging.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "Ongoing management",
    image: "https://www.carehospitals.com/ckfinder/userfiles/images/arthritis.webp",
    symptomsList: "Joint pain; Morning stiffness; Swelling; Difficulty with stairs or walking; Reduced range of motion",
    treatment: "Low-impact strengthening, range-of-motion exercises, joint protection education, balance training, pain-relief modalities.",
    sortOrder: 36,
    active: true,
  },
  {
    title: "Pelvic Girdle Pain",
    slug: "pelvic-girdle-pain",
    iconName: null,
    description: "Pain around the pelvis and hips, commonly experienced during pregnancy.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/prenatal-postnatal-back-pain.jpg",
    symptomsList: "Pain over the pubic bone or sacroiliac joints; Pain with walking, stairs, or turning in bed",
    treatment: "Pelvic girdle stability exercises, manual therapy, activity modification, pregnancy-safe posture training.",
    sortOrder: 37,
    active: true,
  },
  {
    title: "Back Pain in Pregnancy",
    slug: "prenatal-postnatal-back-pain",
    iconName: null,
    description: "Back pain arising from postural and hormonal changes during pregnancy.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/prenatal-postnatal-back-pain.jpg",
    symptomsList: "Lower back/pelvic pain; Discomfort with prolonged standing or walking",
    treatment: "Pregnancy-safe stretching and strengthening, postural correction, pelvic tilt exercises.",
    sortOrder: 38,
    active: true,
  },
  {
    title: "Diastasis Recti",
    slug: "postpartum-recovery-diastasis-recti",
    iconName: null,
    description: "Separation of the abdominal muscles after pregnancy/childbirth.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/postpartum-recovery-diastasis-recti.jpg",
    symptomsList: "Abdominal bulge; Core weakness; Back pain",
    treatment: "Core-rehabilitation exercises, safe abdominal strengthening progression, posture correction.",
    sortOrder: 39,
    active: true,
  },
  {
    title: "Postnatal Core Weakness",
    slug: "postnatal-core-weakness",
    iconName: null,
    description: "Reduced abdominal and pelvic strength after childbirth affecting posture and daily activities.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/postpartum-recovery-diastasis-recti.jpg",
    symptomsList: "Core weakness; Back pain; Poor posture; Difficulty lifting or bending",
    treatment: "Safe core re-activation, deep abdominal and pelvic floor retraining, posture correction, graded strengthening.",
    sortOrder: 40,
    active: true,
  },
  {
    title: "Symphysis Pubis Dysfunction",
    slug: "symphysis-pubis-dysfunction",
    iconName: null,
    description: "Pain and instability at the pubic joint (symphysis pubis), often during or after pregnancy.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/pelvic-pain.jpg",
    symptomsList: "Pain over the pubic bone; Pain with walking, stairs, or lifting one leg; Reduced mobility",
    treatment: "Pelvic stability exercises, mobility aids guidance, activity modification, manual therapy.",
    sortOrder: 41,
    active: true,
  },
  {
    title: "Swelling in Pregnancy",
    slug: "swelling-in-pregnancy",
    iconName: null,
    description: "Fluid retention causing swelling of the hands, feet, and legs during pregnancy.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "2-4 weeks",
    image: "/images/symptoms/urinary-incontinence.jpg",
    symptomsList: "Puffiness in ankles, feet, or hands; Tight feeling over swollen areas; Heaviness in legs",
    treatment: "Gentle ankle and leg movement, elevation guidance, compression advice, pregnancy-safe exercise.",
    sortOrder: 42,
    active: true,
  },
  {
    title: "Urinary Incontinence",
    slug: "urinary-incontinence",
    iconName: null,
    description: "Involuntary leakage of urine, often linked to pelvic floor weakness.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/urinary-incontinence.jpg",
    symptomsList: "Leakage with coughing/sneezing/exercise; Urgency",
    treatment: "Pelvic floor strengthening (Kegel exercises), bladder training, biofeedback.",
    sortOrder: 43,
    active: true,
  },
  {
    title: "Pelvic Organ Prolapse",
    slug: "pelvic-floor-dysfunction",
    iconName: null,
    description: "Descent of pelvic organs caused by weakness or dysfunction of the pelvic floor muscles.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/pelvic-floor-dysfunction.jpg",
    symptomsList: "Pelvic heaviness or bulge; Discomfort; Urinary leakage; Pressure with standing",
    treatment: "Pelvic floor muscle training, biofeedback, posture and lifting guidance, activity modification.",
    sortOrder: 44,
    active: true,
  },
  {
    title: "Chronic Pelvic Pain",
    slug: "pelvic-pain",
    iconName: null,
    description: "Ongoing pain in the pelvic region from muscular, joint, or nerve-related causes.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/pelvic-pain.jpg",
    symptomsList: "Persistent or intermittent pelvic discomfort; Pain with movement or sitting",
    treatment: "Manual therapy, pelvic floor relaxation/strengthening as indicated, postural correction.",
    sortOrder: 45,
    active: true,
  },
  {
    title: "Painful Intercourse (Dyspareunia)",
    slug: "dyspareunia-painful-intercourse",
    iconName: null,
    description: "Vulvar or pelvic pain during or after intercourse, often linked to pelvic floor muscle tightness.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/pelvic-floor-dysfunction.jpg",
    symptomsList: "Pain during or after intercourse; Pelvic tightness; Burning or aching sensation",
    treatment: "Pelvic floor relaxation and stretching, manual therapy, desensitization techniques, pain education.",
    sortOrder: 46,
    active: true,
  },
  {
    title: "Vaginismus",
    slug: "vaginismus",
    iconName: null,
    description: "Involuntary tightening of the pelvic floor muscles causing entry-related pain or difficulty.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/pelvic-floor-dysfunction.jpg",
    symptomsList: "Muscle spasm; Pain or difficulty with penetration; Fear or avoidance of intercourse",
    treatment: "Pelvic floor relaxation techniques, graded desensitization, breathing and mindfulness-based control.",
    sortOrder: 47,
    active: true,
  },
  {
    title: "Faecal Incontinence",
    slug: "faecal-incontinence",
    iconName: null,
    description: "Uncontrolled passage of stool, often caused by pelvic floor weakness or nerve damage.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/urinary-incontinence.jpg",
    symptomsList: "Difficulty controlling bowel movements; Leakage with urgency; Reduced sensation",
    treatment: "Pelvic floor strengthening, bowel retraining, biofeedback, dietary and lifestyle guidance.",
    sortOrder: 48,
    active: true,
  },
];