export interface SeedSymptom {
  title: string;
  slug: string;
  iconName: string | null;
  description: string;
  popularFor: string[];
  recoveryEstimate: string | null;
  image: string | null;
  symptomsList: string;
  treatment: string;
  sortOrder: number;
  active: boolean;
}

export const SYMPTOMS_DATA: SeedSymptom[] = [
  {
    title: "Back Pain (Upper, Lower/Lumbar, Chronic)",
    slug: "back-pain",
    iconName: null,
    description: "Pain along the spine caused by muscle strain, poor posture, disc issues, or prolonged sitting/standing.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "https://i0.wp.com/www.kvphysiotherapy.com/wp-content/uploads/2021/04/WhatsApp-Image-2021-04-19-at-8.29.41-PM.jpeg?resize=1140%2C855&ssl=1",
    symptomsList: "Dull or sharp pain in upper/lower back; Stiffness on waking; Pain worsening with bending or sitting long hours; Muscle spasm",
    treatment: "Postural correction, core-strengthening exercises, manual therapy, heat/electrotherapy, ergonomic advice, stretching program.",
    sortOrder: 1,
    active: true,
  },
  {
    title: "Neck Pain / Cervical Spondylosis",
    slug: "neck-pain-cervical-spondylosis",
    iconName: null,
    description: "Wear-and-tear or strain affecting the cervical (neck) spine, common with age or desk-bound work.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "https://ispcclinic.com/wp-content/uploads/2026/02/b8a18da6-5a02-4d64-b684-e55fd9b488d5-1024x576.jpg",
    symptomsList: "Neck stiffness; Pain radiating to shoulders/arms; Headaches; Reduced neck rotation; Tingling in hands",
    treatment: "Cervical traction, manual mobilization, neck-strengthening exercises, posture retraining, heat therapy.",
    sortOrder: 2,
    active: true,
  },
  {
    title: "Slip Disc / Herniated Disc (Cervical & Lumbar)",
    slug: "slip-disc-herniated-disc",
    iconName: null,
    description: "The soft cushion between spinal vertebrae bulges or ruptures, pressing on nearby nerves.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/slip-disc-herniated-disc.jpg",
    symptomsList: "Sharp localized pain; Radiating pain (arm or leg); Numbness; Tingling; Muscle weakness",
    treatment: "McKenzie exercises, traction therapy, core stabilization, nerve-gliding exercises, pain-relief electrotherapy; surgical referral if red flags present.",
    sortOrder: 3,
    active: true,
  },
  {
    title: "Sciatica",
    slug: "sciatica",
    iconName: null,
    description: "Irritation or compression of the sciatic nerve, usually from a disc issue or piriformis tightness.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "https://www.sakraworldhospital.com/assets/images/blogs/sciatica.webp",
    symptomsList: "Shooting pain from lower back through hip and down the leg; Numbness; Tingling; Worse on sitting",
    treatment: "Nerve mobilization, stretching (piriformis, hamstrings), core strengthening, postural correction, heat/cold therapy.",
    sortOrder: 4,
    active: true,
  },
  {
    title: "Frozen Shoulder (Adhesive Capsulitis)",
    slug: "frozen-shoulder",
    iconName: null,
    description: "Progressive stiffening and thickening of the shoulder joint capsule, restricting movement.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "8-16 weeks",
    image: "https://www.shutterstock.com/image-photo/indian-physiotherapist-help-elderly-man-260nw-2580442099.jpg",
    symptomsList: "Gradual shoulder pain; Severe stiffness; Difficulty raising arm; Night pain",
    treatment: "Capsular stretching, mobilization techniques, pendulum exercises, ultrasound therapy, progressive range-of-motion program.",
    sortOrder: 5,
    active: true,
  },
  {
    title: "Shoulder Pain / Rotator Cuff Injury",
    slug: "shoulder-pain-rotator-cuff",
    iconName: null,
    description: "Damage or inflammation of the muscles/tendons stabilizing the shoulder joint.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/shoulder-pain-rotator-cuff.jpg",
    symptomsList: "Pain with overhead activity; Weakness lifting arm; Clicking sound; Night pain",
    treatment: "Rotator cuff strengthening, scapular stabilization exercises, manual therapy, activity modification.",
    sortOrder: 6,
    active: true,
  },
  {
    title: "Tennis Elbow (Lateral Epicondylitis)",
    slug: "tennis-elbow",
    iconName: null,
    description: "Inflammation of tendons on the outer elbow from repetitive wrist/arm strain.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/tennis-elbow.jpg",
    symptomsList: "Pain on outer elbow; Weak grip; Pain gripping or lifting objects",
    treatment: "Eccentric strengthening exercises, forearm stretching, bracing, ultrasound/laser therapy.",
    sortOrder: 7,
    active: true,
  },
  {
    title: "Golfer's Elbow (Medial Epicondylitis)",
    slug: "golfers-elbow",
    iconName: null,
    description: "Inflammation of tendons on the inner elbow, similar mechanism to tennis elbow but on the opposite side.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/golfers-elbow.jpg",
    symptomsList: "Inner elbow pain; Weak grip strength; Pain with wrist flexion",
    treatment: "Stretching and strengthening of forearm flexors, activity modification, taping, manual therapy.",
    sortOrder: 8,
    active: true,
  },
  {
    title: "Wrist Pain / Carpal Tunnel Syndrome",
    slug: "wrist-pain-carpal-tunnel",
    iconName: null,
    description: "Compression of the median nerve at the wrist, often from repetitive strain.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=600",
    symptomsList: "Numbness/tingling in thumb-index-middle fingers; Weak grip; Night-time symptoms",
    treatment: "Nerve gliding exercises, wrist splinting, ergonomic correction, ultrasound therapy.",
    sortOrder: 9,
    active: true,
  },
  {
    title: "Knee Pain",
    slug: "knee-pain",
    iconName: null,
    description: "Pain due to ligament strain, cartilage wear, or overuse around the knee joint.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "https://www.shutterstock.com/image-photo/indian-doctors-do-health-it-260nw-2657218203.jpg",
    symptomsList: "Pain on walking/climbing stairs; Swelling; Stiffness; Instability",
    treatment: "Quadriceps/hamstring strengthening, taping, gait training, manual therapy.",
    sortOrder: 10,
    active: true,
  },
  {
    title: "Osteoarthritis (Knee, Hip, Hand)",
    slug: "osteoarthritis",
    iconName: null,
    description: "Degeneration of joint cartilage leading to bone-on-bone friction, common with aging.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "https://www.carehospitals.com/ckfinder/userfiles/images/arthritis.webp",
    symptomsList: "Joint pain; Stiffness (especially morning); Swelling; Reduced range of motion; Crepitus",
    treatment: "Low-impact strengthening, range-of-motion exercises, joint protection education, weight-management guidance, pain-relief modalities.",
    sortOrder: 11,
    active: true,
  },
  {
    title: "Rheumatoid Arthritis",
    slug: "rheumatoid-arthritis",
    iconName: null,
    description: "An autoimmune condition causing chronic joint inflammation.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/rheumatoid-arthritis.jpg",
    symptomsList: "Symmetrical joint pain and swelling; Morning stiffness lasting over an hour; Fatigue",
    treatment: "Gentle range-of-motion exercises, joint protection techniques, splinting, pain management (in coordination with rheumatologist).",
    sortOrder: 12,
    active: true,
  },
  {
    title: "Hip Pain / Hip Impingement",
    slug: "hip-pain-hip-impingement",
    iconName: null,
    description: "Abnormal contact between hip bones causing pain and restricted movement.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/hip-pain-hip-impingement.jpg",
    symptomsList: "Groin pain; Stiffness; Pain with prolonged sitting or deep hip flexion",
    treatment: "Hip mobility exercises, glute strengthening, movement pattern correction, manual therapy.",
    sortOrder: 13,
    active: true,
  },
  {
    title: "Ankle Sprain",
    slug: "ankle-sprain",
    iconName: null,
    description: "Stretching or tearing of ligaments around the ankle, usually from a twisting injury.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/ankle-sprain.jpg",
    symptomsList: "Swelling; Bruising; Pain on weight-bearing; Instability",
    treatment: "RICE protocol initially, balance/proprioception training, progressive strengthening, taping.",
    sortOrder: 14,
    active: true,
  },
  {
    title: "Plantar Fasciitis / Heel Pain",
    slug: "plantar-fasciitis-heel-pain",
    iconName: null,
    description: "Inflammation of the plantar fascia (tissue band along the sole of the foot).",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/plantar-fasciitis-heel-pain.jpg",
    symptomsList: "Sharp heel pain; Worst with first steps in the morning; Pain after prolonged standing",
    treatment: "Calf and plantar fascia stretching, foot strengthening, taping, footwear advice, night splints.",
    sortOrder: 15,
    active: true,
  },
  {
    title: "Foot Pain / Flat Feet",
    slug: "foot-pain-flat-feet",
    iconName: null,
    description: "Pain related to arch collapse or abnormal foot mechanics.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "/images/symptoms/foot-pain-flat-feet.jpg",
    symptomsList: "Foot fatigue; Arch pain; Pain radiating to ankle/knee; Uneven shoe wear",
    treatment: "Arch-strengthening exercises, orthotic advice, gait correction, stretching program.",
    sortOrder: 16,
    active: true,
  },
  {
    title: "Scoliosis / Postural Deformities",
    slug: "scoliosis-postural-deformities",
    iconName: null,
    description: "Abnormal curvature or alignment of the spine.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/scoliosis-postural-deformities.jpg",
    symptomsList: "Visible spinal curve; Uneven shoulders/hips; Back pain; Fatigue with prolonged standing",
    treatment: "Scoliosis-specific exercises (e.g., Schroth method), postural correction, core strengthening, bracing guidance where needed.",
    sortOrder: 17,
    active: true,
  },
  {
    title: "Spondylolisthesis",
    slug: "spondylolisthesis",
    iconName: null,
    description: "Forward slippage of one vertebra over another.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/spondylolisthesis.jpg",
    symptomsList: "Lower back pain; Tight hamstrings; Pain radiating to legs; Worsened by standing/walking",
    treatment: "Core stabilization, flexion-based exercises, activity modification, bracing when indicated.",
    sortOrder: 18,
    active: true,
  },
  {
    title: "Ankylosing Spondylitis",
    slug: "ankylosing-spondylitis",
    iconName: null,
    description: "A chronic inflammatory condition affecting the spine and sacroiliac joints.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/ankylosing-spondylitis.jpg",
    symptomsList: "Progressive stiffness; Lower back/hip pain worse at night and in the morning; Reduced spinal flexibility",
    treatment: "Spinal mobility exercises, deep breathing exercises, postural training, regular stretching routine.",
    sortOrder: 19,
    active: true,
  },
  {
    title: "Osteoporosis Management",
    slug: "osteoporosis-management",
    iconName: null,
    description: "Reduced bone density making bones fragile and prone to fracture.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/osteoporosis-management.jpg",
    symptomsList: "Often asymptomatic until a fracture occurs; May include back pain or loss of height",
    treatment: "Weight-bearing exercises, balance training to prevent falls, posture correction, safe strengthening program.",
    sortOrder: 20,
    active: true,
  },
  {
    title: "Fibromyalgia",
    slug: "fibromyalgia",
    iconName: null,
    description: "A chronic condition causing widespread musculoskeletal pain and tenderness.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/fibromyalgia.jpg",
    symptomsList: "Widespread pain; Fatigue; Sleep disturbance; Tender points; Brain fog",
    treatment: "Graded aerobic exercise, gentle stretching, relaxation techniques, pain education, hydrotherapy.",
    sortOrder: 21,
    active: true,
  },
  {
    title: "Myofascial Pain Syndrome",
    slug: "myofascial-pain-syndrome",
    iconName: null,
    description: "Chronic pain from trigger points within tight muscle bands.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/myofascial-pain-syndrome.jpg",
    symptomsList: "Localized deep muscle pain; Referred pain patterns; Palpable knots",
    treatment: "Trigger-point release, dry needling, stretching, myofascial release techniques.",
    sortOrder: 22,
    active: true,
  },
  {
    title: "Muscle Strain / Ligament Tear",
    slug: "muscle-strain-ligament-tear",
    iconName: null,
    description: "Overstretching or tearing of muscle fibers or ligaments.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/muscle-strain-ligament-tear.jpg",
    symptomsList: "Sudden pain; Swelling; Bruising; Reduced strength/movement",
    treatment: "RICE protocol, progressive loading exercises, manual therapy, return-to-activity program.",
    sortOrder: 23,
    active: true,
  },
  {
    title: "Tendinitis / Tendinopathy",
    slug: "tendinitis-tendinopathy",
    iconName: null,
    description: "Inflammation or degeneration of a tendon from overuse.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/tendinitis-tendinopathy.jpg",
    symptomsList: "Localized pain with movement; Tenderness; Swelling; Stiffness",
    treatment: "Eccentric loading exercises, activity modification, ultrasound/shockwave therapy.",
    sortOrder: 24,
    active: true,
  },
  {
    title: "Joint Stiffness",
    slug: "joint-stiffness",
    iconName: null,
    description: "Reduced range of motion in a joint from disuse, injury, or arthritis.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/joint-stiffness.jpg",
    symptomsList: "Difficulty moving the joint fully; Tightness; Discomfort with movement",
    treatment: "Range-of-motion exercises, joint mobilization, stretching program.",
    sortOrder: 25,
    active: true,
  },
  {
    title: "Postural Pain (Tech Neck, Forward Head Posture)",
    slug: "postural-pain-tech-neck",
    iconName: null,
    description: "Musculoskeletal strain from prolonged poor posture, especially from screen use.",
    popularFor: ["Musculoskeletal / Orthopedic"],
    recoveryEstimate: "4-6 weeks",
    image: "/images/symptoms/postural-pain-tech-neck.jpg",
    symptomsList: "Neck/upper back pain; Headaches; Rounded shoulders; Fatigue",
    treatment: "Postural correction exercises, ergonomic workstation advice, strengthening of neck/upper back muscles.",
    sortOrder: 26,
    active: true,
  },
  {
    title: "Post-Fracture Rehabilitation",
    slug: "post-fracture-rehabilitation",
    iconName: null,
    description: "Recovery program after a bone fracture heals, to restore strength and movement.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "6-12 weeks",
    image: "https://sanchetihospital.org/wp-content/uploads/2025/09/rehab_session_2_indian_faces_1440x1440.webp",
    symptomsList: "Joint stiffness; Muscle wasting; Reduced mobility after cast/immobilization removal",
    treatment: "Gradual range-of-motion exercises, strengthening, functional training, scar mobilization if surgical.",
    sortOrder: 27,
    active: true,
  },
  {
    title: "Post Knee Replacement (TKR) Rehab",
    slug: "post-knee-replacement-rehab",
    iconName: null,
    description: "Structured recovery program following total knee replacement surgery.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "8-12 weeks",
    image: "https://t3.ftcdn.net/jpg/08/72/05/32/360_F_872053287_4r8QqUAmvB4R8EeuB3mQNzL8orDKMgrg.jpg",
    symptomsList: "Swelling; Stiffness; Reduced knee bend; Weak quadriceps",
    treatment: "Early mobilization, range-of-motion exercises, quadriceps strengthening, gait training, swelling management.",
    sortOrder: 28,
    active: true,
  },
  {
    title: "Post Hip Replacement (THR) Rehab",
    slug: "post-hip-replacement-rehab",
    iconName: null,
    description: "Recovery program following total hip replacement surgery.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "8-12 weeks",
    image: "/images/symptoms/post-hip-replacement-rehab.jpg",
    symptomsList: "Weakness; Limited hip movement; Altered gait; Precautions on certain movements",
    treatment: "Hip precautions education, progressive strengthening, gait retraining, balance exercises.",
    sortOrder: 29,
    active: true,
  },
  {
    title: "ACL/PCL Reconstruction Rehab",
    slug: "acl-pcl-reconstruction-rehab",
    iconName: null,
    description: "Structured rehabilitation following knee ligament reconstruction surgery.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "9-12 months",
    image: "/images/symptoms/acl-pcl-reconstruction-rehab.jpg",
    symptomsList: "Swelling; Instability; Muscle weakness; Reduced confidence in knee",
    treatment: "Phase-wise strengthening, proprioception training, sport-specific drills, return-to-sport testing.",
    sortOrder: 30,
    active: true,
  },
  {
    title: "Post Spinal Surgery Rehab",
    slug: "post-spinal-surgery-rehab",
    iconName: null,
    description: "Recovery therapy after spinal procedures (discectomy, fusion, laminectomy, etc.).",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/post-spinal-surgery-rehab.jpg",
    symptomsList: "Weakness; Stiffness; Movement fear; Residual nerve symptoms",
    treatment: "Gentle core activation, gradual mobility exercises, posture and body-mechanics education.",
    sortOrder: 31,
    active: true,
  },
  {
    title: "Post Shoulder Surgery Rehab",
    slug: "post-shoulder-surgery-rehab",
    iconName: null,
    description: "Recovery therapy following shoulder surgery (rotator cuff repair, labral repair, etc.).",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/post-shoulder-surgery-rehab.jpg",
    symptomsList: "Stiffness; Weakness; Limited range of motion during recovery phases",
    treatment: "Passive-to-active range-of-motion progression, strengthening phases, scapular control exercises.",
    sortOrder: 32,
    active: true,
  },
  {
    title: "Ligament/Tendon Repair Rehab",
    slug: "ligament-tendon-repair-rehab",
    iconName: null,
    description: "Rehabilitation after surgical repair of a torn ligament or tendon.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/ligament-tendon-repair-rehab.jpg",
    symptomsList: "Stiffness; Weakness; Swelling during healing phases",
    treatment: "Protected mobilization, progressive loading, functional strengthening.",
    sortOrder: 33,
    active: true,
  },
  {
    title: "Amputee/Prosthetic Rehabilitation",
    slug: "amputee-prosthetic-rehabilitation",
    iconName: null,
    description: "Therapy to help patients adapt to life and mobility with a prosthetic limb.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "3-6 months",
    image: "/images/symptoms/amputee-prosthetic-rehabilitation.jpg",
    symptomsList: "Balance difficulty; Phantom limb sensation; Gait abnormalities; Muscle weakness",
    treatment: "Prosthetic training, gait re-education, balance and strength training, desensitization techniques.",
    sortOrder: 34,
    active: true,
  },
  {
    title: "Road Traffic Accident (RTA) Injury Recovery",
    slug: "rta-injury-recovery",
    iconName: null,
    description: "Rehabilitation following trauma sustained in vehicular accidents.",
    popularFor: ["Post-Surgical Rehabilitation"],
    recoveryEstimate: "8-16 weeks",
    image: "/images/symptoms/rta-injury-recovery.jpg",
    symptomsList: "Multiple injuries; Pain; Stiffness; Reduced function; Sometimes whiplash",
    treatment: "Individualized multi-injury rehab plan, pain management, progressive mobility and strength restoration.",
    sortOrder: 35,
    active: true,
  },
  {
    title: "Muscle Pulls & Strains",
    slug: "muscle-pulls-strains",
    iconName: null,
    description: "Overstretching of muscle fibers during physical activity.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/muscle-pulls-strains.jpg",
    symptomsList: "Sudden pain; Tightness; Swelling; Reduced strength",
    treatment: "RICE, progressive stretching and strengthening, return-to-play protocol.",
    sortOrder: 36,
    active: true,
  },
  {
    title: "Ligament Sprains (ACL, MCL, Ankle)",
    slug: "ligament-sprains",
    iconName: null,
    description: "Stretching or tearing of ligaments stabilizing a joint.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/ligament-sprains.jpg",
    symptomsList: "Swelling; Instability; Pain with movement; Bruising",
    treatment: "Bracing, proprioception training, progressive strengthening, sport-specific rehab.",
    sortOrder: 37,
    active: true,
  },
  {
    title: "Meniscus Tear",
    slug: "meniscus-tear",
    iconName: null,
    description: "Tear in the knee's cartilage cushion, often from twisting movements.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/meniscus-tear.jpg",
    symptomsList: "Knee pain; Swelling; Locking or catching sensation; Limited range of motion",
    treatment: "Strengthening exercises, range-of-motion work, activity modification; surgical referral if severe.",
    sortOrder: 38,
    active: true,
  },
  {
    title: "Shin Splints",
    slug: "shin-splints",
    iconName: null,
    description: "Inflammation of muscles/tendons around the shinbone from repetitive stress.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "2-6 weeks",
    image: "/images/symptoms/shin-splints.jpg",
    symptomsList: "Pain along the inner shin during/after activity; Tenderness; Mild swelling",
    treatment: "Rest and load management, calf/shin stretching, strengthening, footwear/gait assessment.",
    sortOrder: 39,
    active: true,
  },
  {
    title: "Runner''s Knee",
    slug: "runners-knee",
    iconName: null,
    description: "Pain around the kneecap from overuse or poor tracking of the patella.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-6 weeks",
    image: "/images/symptoms/runners-knee.jpg",
    symptomsList: "Dull ache around/behind kneecap; Worse with running, squatting, or stairs",
    treatment: "Quadriceps and hip strengthening, patellar taping, gait analysis, stretching.",
    sortOrder: 40,
    active: true,
  },
  {
    title: "Rotator Cuff Strain",
    slug: "rotator-cuff-strain",
    iconName: null,
    description: "Overstretching or minor tearing of shoulder rotator cuff muscles.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/rotator-cuff-strain.jpg",
    symptomsList: "Shoulder pain with overhead movement; Weakness; Discomfort at rest",
    treatment: "Rotator cuff and scapular strengthening, activity modification, manual therapy.",
    sortOrder: 41,
    active: true,
  },
  {
    title: "Stress Fractures",
    slug: "stress-fractures",
    iconName: null,
    description: "Small cracks in bone from repetitive impact or overuse.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "6-8 weeks",
    image: "/images/symptoms/stress-fractures.jpg",
    symptomsList: "Localized pain that worsens with activity; Tenderness; Mild swelling",
    treatment: "Load management, gradual return-to-activity program, strengthening, footwear/biomechanics review.",
    sortOrder: 42,
    active: true,
  },
  {
    title: "Sports-Specific Return-to-Play Rehabilitation",
    slug: "sports-return-to-play",
    iconName: null,
    description: "A structured program to safely return an athlete to their sport after injury.",
    popularFor: ["Sports Injuries"],
    recoveryEstimate: "4-12 weeks",
    image: "https://www.shutterstock.com/image-photo/indian-fallen-injured-senior-man-260nw-2315485911.jpg",
    symptomsList: "Residual weakness; Reduced confidence; Incomplete functional recovery",
    treatment: "Sport-specific drills, agility and strength testing, gradual loading progression, performance testing before clearance.",
    sortOrder: 43,
    active: true,
  },
  {
    title: "Stroke (CVA) Rehabilitation",
    slug: "stroke-rehabilitation",
    iconName: null,
    description: "Recovery therapy after a stroke affecting brain blood supply, causing motor/sensory deficits.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "3-12 months",
    image: "https://t3.ftcdn.net/jpg/06/64/72/70/360_F_664727033_DWgYkD9ZRgPYYIkAu2O5jvM9d8nVtjS.jpg",
    symptomsList: "Weakness on one side; Speech difficulty; Balance problems; Coordination loss",
    treatment: "Task-specific motor retraining, balance training, gait re-education, functional exercises.",
    sortOrder: 44,
    active: true,
  },
  {
    title: "Paralysis (Hemiplegia/Paraplegia)",
    slug: "paralysis-hemiplegia-paraplegia",
    iconName: null,
    description: "Loss of muscle function/movement in part of the body due to neurological damage.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/paralysis-hemiplegia-paraplegia.jpg",
    symptomsList: "Weakness or complete loss of movement; Muscle stiffness/spasticity; Sensory changes",
    treatment: "Neuro-facilitation techniques, strengthening of unaffected/affected muscles, mobility and transfer training.",
    sortOrder: 45,
    active: true,
  },
  {
    title: "Parkinson''s Disease",
    slug: "parkinsons-disease",
    iconName: null,
    description: "A progressive neurological disorder affecting movement control.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/parkinsons-disease.jpg",
    symptomsList: "Tremors; Muscle rigidity; Slow movement; Balance problems; Shuffling gait",
    treatment: "Gait training, balance exercises, flexibility work, functional mobility training.",
    sortOrder: 46,
    active: true,
  },
  {
    title: "Multiple Sclerosis",
    slug: "multiple-sclerosis",
    iconName: null,
    description: "An autoimmune condition affecting the central nervous system.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/multiple-sclerosis.jpg",
    symptomsList: "Fatigue; Muscle weakness; Balance issues; Numbness; Coordination difficulty",
    treatment: "Energy conservation strategies, balance and strengthening exercises, stretching, fatigue-managed activity plans.",
    sortOrder: 47,
    active: true,
  },
  {
    title: "Bell''s Palsy (Facial Palsy)",
    slug: "bells-palsy-facial-palsy",
    iconName: null,
    description: "Sudden weakness or paralysis of facial muscles, usually one-sided.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/bells-palsy-facial-palsy.jpg",
    symptomsList: "Drooping of one side of face; Difficulty closing eye; Altered facial expression",
    treatment: "Facial exercises, neuromuscular re-education, massage, electrical stimulation.",
    sortOrder: 48,
    active: true,
  },
  {
    title: "Cerebral Palsy",
    slug: "cerebral-palsy",
    iconName: null,
    description: "A group of disorders affecting movement and posture due to early brain development issues.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/cerebral-palsy.jpg",
    symptomsList: "Muscle stiffness or floppiness; Poor coordination; Delayed motor milestones",
    treatment: "Developmental therapy, stretching, strengthening, gait training, assistive device training.",
    sortOrder: 49,
    active: true,
  },
  {
    title: "Spinal Cord Injury",
    slug: "spinal-cord-injury",
    iconName: null,
    description: "Damage to the spinal cord causing loss of function below the injury level.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/spinal-cord-injury.jpg",
    symptomsList: "Weakness or paralysis; Sensory loss; Muscle spasticity; Bladder/bowel changes",
    treatment: "Mobility and transfer training, strengthening of functional muscles, wheelchair skills training, spasticity management.",
    sortOrder: 50,
    active: true,
  },
  {
    title: "Peripheral Neuropathy",
    slug: "peripheral-neuropathy",
    iconName: null,
    description: "Damage to peripheral nerves causing weakness and sensory changes, often in hands/feet.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/peripheral-neuropathy.jpg",
    symptomsList: "Numbness; Tingling; Burning pain; Muscle weakness",
    treatment: "Sensory re-education, balance training, strengthening exercises, gait aids as needed.",
    sortOrder: 51,
    active: true,
  },
  {
    title: "Guillain-Barré Syndrome",
    slug: "guillain-barre-syndrome",
    iconName: null,
    description: "An autoimmune condition causing rapid-onset muscle weakness.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "3-12 months",
    image: "/images/symptoms/guillain-barre-syndrome.jpg",
    symptomsList: "Progressive weakness; Tingling; Reduced reflexes; Fatigue",
    treatment: "Gradual strengthening, respiratory exercises if needed, functional mobility retraining.",
    sortOrder: 52,
    active: true,
  },
  {
    title: "Vertigo / BPPV (Vestibular Rehabilitation)",
    slug: "vertigo-bppv-vestibular-rehabilitation",
    iconName: null,
    description: "Disorders of the inner ear causing dizziness and balance disturbance.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "2-8 weeks",
    image: "/images/symptoms/vertigo-bppv-vestibular-rehabilitation.jpg",
    symptomsList: "Spinning sensation; Imbalance; Nausea; Unsteady gait",
    treatment: "Canalith repositioning maneuvers (e.g., Epley), vestibular adaptation exercises, balance training.",
    sortOrder: 53,
    active: true,
  },
  {
    title: "Balance & Coordination Disorders",
    slug: "balance-coordination-disorders",
    iconName: null,
    description: "Impaired ability to maintain stability and coordinate movement, from various causes.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/balance-coordination-disorders.jpg",
    symptomsList: "Frequent falls; Unsteadiness; Difficulty with coordinated movements",
    treatment: "Balance training, proprioceptive exercises, strength and gait training.",
    sortOrder: 54,
    active: true,
  },
  {
    title: "Nerve Compression / Radiculopathy",
    slug: "nerve-compression-radiculopathy",
    iconName: null,
    description: "Compression of a spinal nerve root causing pain along its distribution.",
    popularFor: ["Neurological Conditions"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/nerve-compression-radiculopathy.jpg",
    symptomsList: "Radiating pain; Numbness; Tingling; Weakness in the affected limb",
    treatment: "Nerve gliding exercises, traction, postural correction, strengthening.",
    sortOrder: 55,
    active: true,
  },
  {
    title: "Developmental Delay",
    slug: "developmental-delay",
    iconName: null,
    description: "Slower-than-typical achievement of motor milestones in children.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "3-12 months",
    image: "/images/symptoms/developmental-delay.jpg",
    symptomsList: "Delayed sitting/crawling/walking; Poor coordination for age",
    treatment: "Play-based motor development therapy, strengthening, milestone-focused activities.",
    sortOrder: 56,
    active: true,
  },
  {
    title: "Cerebral Palsy (Children)",
    slug: "cerebral-palsy-children",
    iconName: null,
    description: "A movement and posture disorder from early brain development issues, managed early in childhood.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/cerebral-palsy-children.jpg",
    symptomsList: "Abnormal muscle tone; Delayed milestones; Coordination difficulties",
    treatment: "Early intervention therapy, stretching, functional movement training, family education.",
    sortOrder: 57,
    active: true,
  },
  {
    title: "Torticollis",
    slug: "torticollis",
    iconName: null,
    description: "Tightness of neck muscles causing the head to tilt to one side, common in infants.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "3-6 months",
    image: "/images/symptoms/torticollis.jpg",
    symptomsList: "Head tilt; Limited neck rotation; Asymmetrical head shape in infants",
    treatment: "Stretching exercises, positioning techniques, strengthening of opposite-side muscles.",
    sortOrder: 58,
    active: true,
  },
  {
    title: "Clubfoot Post-Correction Therapy",
    slug: "clubfoot-post-correction-therapy",
    iconName: null,
    description: "Therapy following correction of a congenital foot deformity.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "6-12 months",
    image: "/images/symptoms/clubfoot-post-correction-therapy.jpg",
    symptomsList: "Residual stiffness; Weakness; Gait abnormality",
    treatment: "Stretching, strengthening, gait training, bracing compliance support.",
    sortOrder: 59,
    active: true,
  },
  {
    title: "Down Syndrome — Motor Development Therapy",
    slug: "down-syndrome-motor-development",
    iconName: null,
    description: "Supportive therapy addressing low muscle tone and delayed motor development in children with Down syndrome.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/down-syndrome-motor-development.jpg",
    symptomsList: "Low muscle tone (hypotonia); Delayed milestones; Joint hypermobility",
    treatment: "Strengthening exercises, balance and coordination training, milestone-focused developmental activities.",
    sortOrder: 60,
    active: true,
  },
  {
    title: "Muscular Dystrophy",
    slug: "muscular-dystrophy",
    iconName: null,
    description: "A genetic disorder causing progressive muscle weakness.",
    popularFor: ["Pediatric Conditions"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/muscular-dystrophy.jpg",
    symptomsList: "Progressive weakness; Difficulty walking/climbing stairs; Frequent falls",
    treatment: "Gentle strengthening, stretching to prevent contractures, mobility aids training, breathing exercises.",
    sortOrder: 61,
    active: true,
  },
  {
    title: "Pre- and Post-Natal (Pregnancy) Back Pain",
    slug: "prenatal-postnatal-back-pain",
    iconName: null,
    description: "Back pain arising from postural and hormonal changes during/after pregnancy.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/prenatal-postnatal-back-pain.jpg",
    symptomsList: "Lower back/pelvic pain; Discomfort with prolonged standing or walking",
    treatment: "Pregnancy-safe stretching and strengthening, postural correction, pelvic tilt exercises.",
    sortOrder: 62,
    active: true,
  },
  {
    title: "Postpartum Recovery / Diastasis Recti",
    slug: "postpartum-recovery-diastasis-recti",
    iconName: null,
    description: "Separation of abdominal muscles after pregnancy/childbirth.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/postpartum-recovery-diastasis-recti.jpg",
    symptomsList: "Abdominal bulge; Core weakness; Back pain",
    treatment: "Core-rehabilitation exercises, safe abdominal strengthening progression, posture correction.",
    sortOrder: 63,
    active: true,
  },
  {
    title: "Pelvic Floor Dysfunction",
    slug: "pelvic-floor-dysfunction",
    iconName: null,
    description: "Weakness or dysfunction of the pelvic floor muscles.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/pelvic-floor-dysfunction.jpg",
    symptomsList: "Pelvic heaviness; Discomfort; Urinary leakage; Pain during intercourse",
    treatment: "Pelvic floor muscle training, biofeedback, relaxation techniques.",
    sortOrder: 64,
    active: true,
  },
  {
    title: "Urinary Incontinence",
    slug: "urinary-incontinence",
    iconName: null,
    description: "Involuntary leakage of urine, often linked to pelvic floor weakness.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "6-12 weeks",
    image: "/images/symptoms/urinary-incontinence.jpg",
    symptomsList: "Leakage with coughing/sneezing/exercise; Urgency",
    treatment: "Pelvic floor strengthening (Kegel exercises), bladder training, biofeedback.",
    sortOrder: 65,
    active: true,
  },
  {
    title: "Pelvic Pain",
    slug: "pelvic-pain",
    iconName: null,
    description: "Pain in the pelvic region from muscular, joint, or nerve-related causes.",
    popularFor: ["Women's Health"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/pelvic-pain.jpg",
    symptomsList: "Persistent or intermittent pelvic discomfort; Pain with movement or sitting",
    treatment: "Manual therapy, pelvic floor relaxation/strengthening as indicated, postural correction.",
    sortOrder: 66,
    active: true,
  },
  {
    title: "Age-Related Mobility Decline",
    slug: "age-related-mobility-decline",
    iconName: null,
    description: "Gradual reduction in strength, flexibility, and mobility with aging.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "Ongoing management",
    image: "https://advaithability.com/wp-content/uploads/2026/04/Geriatric-Physiotherapy-in-Dehradun.jpg.jpeg",
    symptomsList: "Slower walking; Difficulty rising from chairs; Reduced endurance",
    treatment: "Functional strengthening, flexibility exercises, endurance training.",
    sortOrder: 67,
    active: true,
  },
  {
    title: "Fall-Risk & Balance Training",
    slug: "fall-risk-balance-training",
    iconName: null,
    description: "Assessment and training to reduce the risk of falls in older adults.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/fall-risk-balance-training.jpg",
    symptomsList: "Unsteady gait; History of falls; Reduced confidence in mobility",
    treatment: "Balance exercises, strength training, gait aids assessment, home-safety education.",
    sortOrder: 68,
    active: true,
  },
  {
    title: "Osteoporosis-Related Fragility",
    slug: "osteoporosis-related-fragility",
    iconName: null,
    description: "Increased fracture risk due to reduced bone density.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/osteoporosis-related-fragility.jpg",
    symptomsList: "Often silent; May include back pain or stooped posture",
    treatment: "Weight-bearing and resistance exercises, balance training, posture education, fall-prevention strategies.",
    sortOrder: 69,
    active: true,
  },
  {
    title: "General Deconditioning / Weakness",
    slug: "general-deconditioning-weakness",
    iconName: null,
    description: "Loss of strength and stamina from inactivity or prolonged illness.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/general-deconditioning-weakness.jpg",
    symptomsList: "Fatigue; Weakness; Reduced tolerance for daily activities",
    treatment: "Graded exercise program, functional training, endurance building.",
    sortOrder: 70,
    active: true,
  },
  {
    title: "Post-Hospitalization Recovery",
    slug: "post-hospitalization-recovery",
    iconName: null,
    description: "Rehabilitation to regain strength and independence after a hospital stay.",
    popularFor: ["Geriatric Care"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/post-hospitalization-recovery.jpg",
    symptomsList: "Weakness; Reduced mobility; Deconditioning",
    treatment: "Progressive mobility and strengthening program, functional activity training.",
    sortOrder: 71,
    active: true,
  },
  {
    title: "Post-Cardiac Surgery Rehabilitation (Cardiac Rehab)",
    slug: "cardiac-rehabilitation",
    iconName: null,
    description: "Structured exercise and education program after heart surgery or a cardiac event.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "8-12 weeks",
    image: "/images/symptoms/cardiac-rehabilitation.jpg",
    symptomsList: "Reduced stamina; Weakness; Anxiety about exertion",
    treatment: "Graded aerobic exercise, breathing exercises, monitored strength training, lifestyle education.",
    sortOrder: 72,
    active: true,
  },
  {
    title: "COPD (Chronic Obstructive Pulmonary Disease)",
    slug: "copd",
    iconName: null,
    description: "A progressive lung disease causing airflow limitation.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/copd.jpg",
    symptomsList: "Breathlessness; Chronic cough; Fatigue; Reduced exercise tolerance",
    treatment: "Pulmonary rehabilitation, breathing exercises, airway clearance techniques, graded exercise training.",
    sortOrder: 73,
    active: true,
  },
  {
    title: "Asthma — Breathing Exercises",
    slug: "asthma-breathing-exercises",
    iconName: null,
    description: "A chronic condition causing airway inflammation and breathing difficulty.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/asthma-breathing-exercises.jpg",
    symptomsList: "Wheezing; Breathlessness; Chest tightness; Coughing",
    treatment: "Breathing retraining, diaphragmatic breathing exercises, posture correction, graded activity.",
    sortOrder: 74,
    active: true,
  },
  {
    title: "Post-COVID Pulmonary Rehabilitation",
    slug: "post-covid-pulmonary-rehabilitation",
    iconName: null,
    description: "Recovery therapy for lingering respiratory and functional effects after COVID-19.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/post-covid-pulmonary-rehabilitation.jpg",
    symptomsList: "Breathlessness; Fatigue; Reduced stamina; Muscle weakness",
    treatment: "Breathing exercises, graded aerobic reconditioning, strength training, fatigue management.",
    sortOrder: 75,
    active: true,
  },
  {
    title: "Chest Physiotherapy (Secretion Clearance)",
    slug: "chest-physiotherapy",
    iconName: null,
    description: "Techniques to help clear mucus/secretions from the lungs.",
    popularFor: ["Cardio-Respiratory"],
    recoveryEstimate: "2-4 weeks",
    image: "/images/symptoms/chest-physiotherapy.jpg",
    symptomsList: "Chest congestion; Difficulty clearing secretions; Breathlessness",
    treatment: "Postural drainage, percussion/vibration techniques, breathing exercises, coughing techniques.",
    sortOrder: 76,
    active: true,
  },
  {
    title: "Chronic Lower Back Pain",
    slug: "chronic-lower-back-pain",
    iconName: null,
    description: "Persistent back pain lasting more than 3 months, often multifactorial.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/chronic-lower-back-pain.jpg",
    symptomsList: "Ongoing dull or sharp pain; Stiffness; Activity limitation",
    treatment: "Graded exercise therapy, pain education, core strengthening, lifestyle modification.",
    sortOrder: 77,
    active: true,
  },
  {
    title: "Migraine/Tension Headache (Posture-Related)",
    slug: "migraine-tension-headache",
    iconName: null,
    description: "Recurring headaches linked to muscular tension or postural strain.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/migraine-tension-headache.jpg",
    symptomsList: "Head pain; Neck/shoulder tightness; Sometimes light sensitivity",
    treatment: "Postural correction, neck and shoulder relaxation exercises, manual therapy, ergonomic advice.",
    sortOrder: 78,
    active: true,
  },
  {
    title: "Sedentary Lifestyle-Related Stiffness",
    slug: "sedentary-lifestyle-stiffness",
    iconName: null,
    description: "Muscular tightness and reduced mobility from prolonged inactivity.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "2-4 weeks",
    image: "/images/symptoms/sedentary-lifestyle-stiffness.jpg",
    symptomsList: "General stiffness; Fatigue; Reduced flexibility",
    treatment: "Mobility exercises, stretching routines, activity-level guidance.",
    sortOrder: 79,
    active: true,
  },
  {
    title: "Obesity-Related Joint Pain",
    slug: "obesity-related-joint-pain",
    iconName: null,
    description: "Joint stress and pain linked to excess body weight.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/obesity-related-joint-pain.jpg",
    symptomsList: "Knee/hip/back pain; Reduced mobility; Fatigue with activity",
    treatment: "Low-impact strengthening, weight-management guided exercise, joint-protection education.",
    sortOrder: 80,
    active: true,
  },
  {
    title: "Diabetic Neuropathy-Related Mobility Issues",
    slug: "diabetic-neuropathy-mobility",
    iconName: null,
    description: "Nerve damage from diabetes affecting sensation and movement, usually in the feet.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "Ongoing management",
    image: "/images/symptoms/diabetic-neuropathy-mobility.jpg",
    symptomsList: "Numbness; Tingling; Balance difficulty; Foot weakness",
    treatment: "Balance training, foot-care education, sensory re-education, gait training.",
    sortOrder: 81,
    active: true,
  },
  {
    title: "Repetitive Strain Injury (RSI) from Desk Work",
    slug: "repetitive-strain-injury-desk-work",
    iconName: null,
    description: "Overuse injury of muscles/tendons from repetitive movements or poor ergonomics.",
    popularFor: ["Chronic Pain & Lifestyle"],
    recoveryEstimate: "4-6 weeks",
    image: "/images/symptoms/repetitive-strain-injury-desk-work.jpg",
    symptomsList: "Pain, tingling, or weakness in wrists, hands, neck, or shoulders",
    treatment: "Ergonomic correction, stretching and strengthening, activity modification, manual therapy.",
    sortOrder: 82,
    active: true,
  },
  {
    title: "Manual Therapy / Manipulation",
    slug: "manual-therapy",
    iconName: null,
    description: "Hands-on technique using mobilization or manipulation of joints and soft tissue to relieve pain and restore movement.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Varies by condition",
    image: "/images/symptoms/manual-therapy.jpg",
    symptomsList: "Joint stiffness; Muscle tightness; Restricted movement; Pain with motion",
    treatment: "Joint mobilization, soft tissue manipulation, thrust techniques, muscle energy techniques.",
    sortOrder: 83,
    active: true,
  },
  {
    title: "Dry Needling",
    slug: "dry-needling",
    iconName: null,
    description: "Fine needles inserted into trigger points to release muscle tightness and reduce pain.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "2-4 sessions",
    image: "/images/symptoms/dry-needling.jpg",
    symptomsList: "Muscle knots; Trigger points; Referred pain patterns; Localized tightness",
    treatment: "Intramuscular stimulation, trigger point release, dry needling of active trigger points.",
    sortOrder: 84,
    active: true,
  },
  {
    title: "Cupping Therapy",
    slug: "cupping-therapy",
    iconName: null,
    description: "Suction cups applied to the skin to improve blood flow and relieve muscle tension.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "1-3 sessions",
    image: "/images/symptoms/cupping-therapy.jpg",
    symptomsList: "Muscle tension; Poor circulation; Myofascial tightness; Stiffness",
    treatment: "Static cupping, dynamic cupping, flash cupping, combination with other modalities.",
    sortOrder: 85,
    active: true,
  },
  {
    title: "Electrotherapy (IFT, TENS, Ultrasound Therapy)",
    slug: "electrotherapy",
    iconName: null,
    description: "Electrical/sound wave-based modalities used for pain relief, inflammation reduction, and tissue healing.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Varies by condition",
    image: "/images/symptoms/electrotherapy.jpg",
    symptomsList: "Acute or chronic pain; Inflammation; Muscle spasm; Delayed tissue healing",
    treatment: "Interferential therapy (IFT), transcutaneous electrical nerve stimulation (TENS), therapeutic ultrasound.",
    sortOrder: 86,
    active: true,
  },
  {
    title: "Kinesiology Taping",
    slug: "kinesiology-taping",
    iconName: null,
    description: "Elastic tape applied to support muscles/joints, reduce pain, and improve movement awareness.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Immediate support",
    image: "/images/symptoms/kinesiology-taping.jpg",
    symptomsList: "Muscle fatigue; Joint instability; Swelling; Movement pain",
    treatment: "Fascial correction, muscle facilitation/inhibition, ligament support, lymphatic drainage taping.",
    sortOrder: 87,
    active: true,
  },
  {
    title: "Traction Therapy (Cervical/Lumbar)",
    slug: "traction-therapy",
    iconName: null,
    description: "Mechanical or manual stretching of the spine to relieve nerve compression and disc pressure.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/traction-therapy.jpg",
    symptomsList: "Nerve compression; Disc herniation; Radiculopathy; Spinal stenosis symptoms",
    treatment: "Mechanical traction, manual traction, intermittent traction, sustained traction.",
    sortOrder: 88,
    active: true,
  },
  {
    title: "Shockwave Therapy",
    slug: "shockwave-therapy",
    iconName: null,
    description: "High-energy sound waves used to treat chronic tendon injuries and stimulate healing.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "3-6 sessions",
    image: "/images/symptoms/shockwave-therapy.jpg",
    symptomsList: "Chronic tendinopathy; Heel pain; Calcific shoulder; Tennis elbow",
    treatment: "Focused shockwave therapy, radial shockwave therapy, combined with exercise prescription.",
    sortOrder: 89,
    active: true,
  },
  {
    title: "Laser Therapy (LASER/LLLT)",
    slug: "laser-therapy",
    iconName: null,
    description: "Low-level laser used to reduce inflammation, relieve pain, and accelerate tissue repair.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Varies by condition",
    image: "/images/symptoms/laser-therapy.jpg",
    symptomsList: "Soft tissue inflammation; Joint pain; Wound healing delay; Muscle strain",
    treatment: "Low-level laser therapy (LLLT), photobiomodulation, class 3B/4 laser applications.",
    sortOrder: 90,
    active: true,
  },
  {
    title: "Exercise Therapy / Strengthening Programs",
    slug: "exercise-therapy",
    iconName: null,
    description: "Customized exercise regimens to build strength, flexibility, and endurance for recovery.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "4-12 weeks",
    image: "/images/symptoms/exercise-therapy.jpg",
    symptomsList: "Muscle weakness; Deconditioning; Reduced endurance; Post-injury weakness",
    treatment: "Progressive resistance training, flexibility programs, cardiovascular conditioning, functional exercise.",
    sortOrder: 91,
    active: true,
  },
  {
    title: "Postural Correction Therapy",
    slug: "postural-correction-therapy",
    iconName: null,
    description: "Targeted exercises and education to correct poor posture and prevent related pain.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/postural-correction-therapy.jpg",
    symptomsList: "Postural imbalance; Forward head; Rounded shoulders; Lower crossed syndrome",
    treatment: "Postural assessment, corrective exercises, ergonomic education, strengthening of weak muscle groups.",
    sortOrder: 92,
    active: true,
  },
  {
    title: "Vestibular Rehabilitation",
    slug: "vestibular-rehabilitation",
    iconName: null,
    description: "Specialized exercises to treat dizziness, imbalance, and inner-ear related disorders.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "4-8 weeks",
    image: "/images/symptoms/vestibular-rehabilitation.jpg",
    symptomsList: "Dizziness; Vertigo; Balance problems; Motion sensitivity",
    treatment: "Canalith repositioning, vestibular adaptation exercises, gaze stabilization, balance retraining.",
    sortOrder: 93,
    active: true,
  },
  {
    title: "Sports Taping",
    slug: "sports-taping",
    iconName: null,
    description: "Taping techniques used to support muscles/joints during sports activity and prevent injury.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Immediate support",
    image: "/images/symptoms/sports-taping.jpg",
    symptomsList: "Joint instability; Muscle weakness; Preventive support needs",
    treatment: "Rigid taping, elastic taping, preventive strapping, proprioceptive taping.",
    sortOrder: 94,
    active: true,
  },
  {
    title: "Cryotherapy / Heat Therapy",
    slug: "cryotherapy-heat-therapy",
    iconName: null,
    description: "Cold or heat application to reduce inflammation, relieve pain, and relax muscles.",
    popularFor: ["Therapy Techniques"],
    recoveryEstimate: "Immediate relief",
    image: "/images/symptoms/cryotherapy-heat-therapy.jpg",
    symptomsList: "Acute injury swelling; Chronic muscle stiffness; Pain; Spasm",
    treatment: "Ice packs, cold compression, hot packs, contrast therapy, warm-up/cool-down protocols.",
    sortOrder: 95,
    active: true,
  },
];
